application:
    build: application
    volumes:
        - ./symfony:/var/www/symfony
        - ./logs/symfony:/var/www/symfony/app/logs
    tty: true

php:
    build: php-fpm
    ports:
        - 9000:9000
    volumes_from:
        - application
    links :
        - db:db

apache:
    build: apache
    ports:
        - 82:80
    links:
        - php:php
    volumes_from:
        - application
    volumes:
        - ./logs/apache/:/var/log/apache2

reverseproxy:
    build: apache-reverseproxy
    ports:
        - 443:443
        - 1337:1337
    volumes_from:
        - application
    volumes:
        - ./logs/reverseproxy/:/var/log/apache2
    extra_hosts:
        - "symfony.local:192.168.99.100"
        - "docker.local:192.168.99.100"

db:
    image: postgres
    restart: always
    ports:
        - 5433:5432
    volumes:
        - ./data/postgres:/tmp
    environment:
        - POSTGRES_PASSWORD=relaischateaux
        - POSTGRES_USER=relaischateaux
        - POSTGRES_DB=relaischateaux

memcached:
    image: memcached:1.4
    ports:
        - 11222:11211

elasticsearch:
    image: elasticsearch:1.5
    command: elasticsearch -Des.network.bind_host=0.0.0.0
    ports:
        - 9200:9200

node:
    build: node
    ports:
        - 1338:8888
    volumes:
        - ./symfony/nodejs:/usr/src/app
        - ./logs/node:/usr/src/app/logs
